/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

/**
 *
 * @author gusta
 */
public class JanelaProgressLogin extends javax.swing.JFrame {

    /**
     * Creates new form JanelaProgressLogin
     */
    public JanelaProgressLogin() {
        initComponents();
        
        new Thread(){
            @Override
            public void run()
            {
                int m;
                for (m = 0; m < 101; m++)
                {
                    try 
                    {
                        sleep(40);
                        
                        jProgressBar1.setValue(m);
                        
                        if (jProgressBar1.getValue() < 34)
                        {
                            jLabel1.setText("Paneko games apresenta...");
                        }
                        else if(jProgressBar1.getValue() < 45)
                        {
                            jLabel1.setText("Erma: the game");
                        }
                        else if(jProgressBar1.getValue() < 79)
                        {
                            jLabel1.setText("Carregando dados...");
                        }
                        else if(jProgressBar1.getValue() < 89)
                        {
                            jLabel1.setText("Seja Bem Vindo!");
                        }
                        else if(100 == jProgressBar1.getValue())
                        {
                            setVisible(false);
                            
                            JanelaLogin batata = new JanelaLogin();
                            batata.setVisible(rootPaneCheckingEnabled);
                        }
                    }
                    catch (InterruptedException ex)
                    {
                        
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONG ");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jProgressBar1.setBackground(new java.awt.Color(102, 0, 255));
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 200, 230, 14);

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 220, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pav.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 260);

        setSize(new java.awt.Dimension(253, 262));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProgressLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProgressLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProgressLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProgressLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaProgressLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
